# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - name: Setup Node.js & pnpm
        uses: unlike-ltd/github-actions/setup-pnpm@4f6c1e5b04525aa73e680f900c9f588f868735e3 #v1.0.0
        with:
          node-version: 20.x
      - name: Build
        run: pnpm run build
      - name: Publish to Cloudflare Pages
        uses: unlike-ltd/github-actions-cloudflare-pages@8c09c46bd39321b4aa3784852491d9e4f09e1566 #v1.2.0
        id: pages
        with:
          cloudflare-api-token: ${{ secrets.CF_PAGES_API_TOKEN }}
          cloudflare-account-id: dd062b3fa5b21455e7c9f8ab5df29bb2
          cloudflare-project-name: serverless-webapp
          directory: build
          github-token: ${{ secrets.CF_API_TK }}
